=== repositive/frontend_exercise/schemas/discussion.schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "title": "Discussion",
    "description": "Defines the format of the GET /discussion/<id> endpoint",
    "type": "object",
    "properties": {
        "id": {
            "type": "string"
        },
        "user_id": {
            "type": "string"
        },
        "text": {
            "type": "string"
        },
        "model": {
            "enum": ["dataset", "request"]
        },
        "model_id": {
            "type": "string"
        },
        "created_at": {
            "type": "string"
        }
    },
    "required": [
        "id",
        "user_id",
        "text",
        "model",
        "model_id",
        "created_at"
    ]
}

=== repositive/frontend_exercise/examples/discussion/6e3d5b6b-9534-4717-b9ec-a20b8b257442.json
{
 "id":"6e3d5b6b-9534-4717-b9ec-a20b8b257442",
 "user_id": "045cbcac-a9a2-4c3d-8c3f-5f005aa47643",
 "created_at": "2017-04-10T18:50:12.171Z",
 "model": "dataset",
 "model_id": "2f93ba6f-fb31-4db9-b83c-98191528f2d1",
 "text": "The data provided is not relevant without controls. Does anyone found some?"
}

=== repositive/frontend_exercise/examples/discussion/262910d5-5b69-432b-aa12-4d1420326c52.json
{
 "id":"6e3d5b6b-9534-4717-b9ec-a20b8b257442",
 "user_id": "045cbcac-a9a2-4c3d-8c3f-5f005aa47643",
 "created_at": "2017-04-16T00:42:17.631Z",
 "model": "request",
 "model_id": "61e18ecb-93ab-4e98-a3c4-e6f9e877cb0e",
 "text": "Have you tried searching using the `datasource: DBGAP`?\n\n I managed to find some interesting data there."
}
