=== repositive/frontend_exercise/schemas/request.schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "title": "Request",
    "description": "Defines the format of the GET /request/<id> endpoint",
    "type": "object",
    "properties": {
        "id": {
            "type": "string"
        },
        "title": {
            "type": "string"
        },
        "description": {
            "type": "string"
        },
        "user_id": {
            "type": "string"
        },
        "created_at": {
            "type": "string"
        }
    },
    "required": [
        "id",
        "title",
        "description",
        "user_id",
        "created_at"
    ]
}

=== repositive/frontend_exercise/examples/request/61e18ecb-93ab-4e98-a3c4-e6f9e877cb0e.json
{
 "id": "61e18ecb-93ab-4e98-a3c4-e6f9e877cb0e",
 "title": "Autism PCR-free whole genome sequencing data",
 "description": "I am trying to start an autism sequencing project. If you have PCR-free whole genome sequencing data from autism patients, please let me know. Maybe we can collaborate in the future.",
 "user_id": "1a3c7f8d-c97a-4480-932b-68d3c771b8b3",
 "created_at": "2017-04-12T00:23:19.653Z"
}
