=== repositive/frontend_exercise/schemas/user.schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "title": "User",
    "description": "Defines the format of the GET /user/<id> endpoint",
    "type": "object",
    "properties": {
        "id": {
            "type": "string"
        },
        "firstname": {
            "type": "string"
        },
        "lastname": {
            "type": "string"
        },
        "avatar": {
            "type": "string"
        },
        "company": {
            "type": "string"
        },
        "work_role": {
            "type": "string"
        },
        "created_at": {
            "type": "string"
        }
    },
    "required": [
        "id",
        "firstname",
        "lastname",
        "avatar",
        "created_at"
    ]
}

=== repositive/frontend_exercise/examples/user/02fe16a3-2602-49c0-86a7-b88aebcdb838.json
{
  "id": "02fe16a3-2602-49c0-86a7-b88aebcdb838",
  "firstname": "Tom",
  "lastname": "Bombadil",
  "avatar": "https://dg2kcfbxc77v1.cloudfront.net/assets/images/avatar/turtle-be4183af0f9b5268439d4193e8da743d.png",
  "work_role": "Neoplasm Researcher",
  "company": "Illumina",
  "created_at": "2017-04-16T23:59:14.648Z"
}

=== repositive/frontend_exercise/examples/user/045cbcac-a9a2-4c3d-8c3f-5f005aa47643.json
{
  "id": "045cbcac-a9a2-4c3d-8c3f-5f005aa47643",
  "firstname": "Istar",
  "lastname": "Eldritch",
  "avatar": "https://dg2kcfbxc77v1.cloudfront.net/assets/images/avatar/turtle-be4183af0f9b5268439d4193e8da743d.png",
  "work_role": "Backend Developer",
  "company": "Repositive",
  "created_at": "2017-04-16T23:59:14.648Z"
}
